In [3]:
#Imports
import pandas as pd
import numpy as np
import matplotlib_inline as plt

In [2]:
%pip install pandas-datareader

Collecting pandas-datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 kB 1.1 MB/s eta 0:00:00a 0:00:01
Collecting lxml (from pandas-datareader)
  Downloading lxml-4.9.3.tar.gz (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 757.0 kB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas>=0.23 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas-datareader) (2.1.1)
Requirement already satisfied: requests>=2.19.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas-datareader) (2.28.1)
Requirement already satisfied: numpy>=1.22.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=0.23->pandas-datareader) (1.23.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/comreton/Library/Python/3.10/lib/python/site-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=0.23->pandas-datareader) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=0.23->pandas-datareader) (2023.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader) (2022.6.15)
Requirement already satisfied: six>=1.5 in /Users/comreton/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-datareader) (1.16.0)
Building wheels for collected packages: lxml
  Building wheel for lxml (pyproject.toml) ... done
  Created wheel for lxml: filename=lxml-4.9.3-cp310-cp310-macosx_10_9_universal2.whl size=3207107 sha256=3fd17ee965be05de3bc030ae1e851e1b811cd213ebf3add0b326ffa149dfcae1
  Stored in directory: /Users/comreton/Library/Caches/pip/wheels/38/0b/56/fd5ffdd76481c9220a131ff39258963d8384599f0109b688d0
Successfully built lxml
Installing collected packages: lxml, pandas-datareader
Successfully installed lxml-4.9.3 pandas-datareader-0.10.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
from pandas_datareader.data import DataReader

In [4]:
%pip install yfinance

Collecting yfinance
  Obtaining dependency information for yfinance from https://files.pythonhosted.org/packages/e6/b3/388ab967a387cc92926f70e97688dd9a7189b29a0773db815ffc5289e2b5/yfinance-0.2.31-py2.py3-none-any.whl.metadata
  Downloading yfinance-0.2.31-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yfinance) (2.1.1)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yfinance) (1.23.2)
Collecting requests>=2.31 (from yfinance)
  Obtaining dependency information for requests>=2.31 from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: lxml>=4.9.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yfinance) (4.9.3)
Collecting appdirs>=1.4.4 (from yfinance)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pytz>=2022.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yfinance) (2023.3.post1)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.3.8-cp310-cp310-macosx_11_0_arm64.whl (35 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.17.0.tar.gz (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 1.1 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yfinance) (4.11.1)
Collecting html5lib>=1.1 (from yfinance)
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 1.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.2.post1)
Requirement already satisfied: six>=1.9 in /Users/comreton/Library/Python/3.10/lib/python/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Collecting webencodings (from html5lib>=1.1->yfinance)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/comreton/Library/Python/3.10/lib/python/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.31->yfinance) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2022.6.15)
Downloading yfinance-0.2.31-py2.py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 614.8 kB/s eta 0:00:00 0:00:01
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 3.3 MB/s eta 0:00:00
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.17.0-cp310-cp310-macosx_10_9_universal2.whl size=380469 sha256=a1fdde349fd84fa5f38b2ba98d912337aff96da584a116cd1baaba634a1a9a74
  Stored in directory: /Users/comreton/Library/Caches/pip/wheels/c7/70/ad/212867e96e7004265a69c4aa5dcff00a95f547a67ba26e7e76
Successfully built peewee
Installing collected packages: webencodings, peewee, multitasking, appdirs, requests, html5lib, frozendict, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
Successfully installed appdirs-1.4.4 frozendict-2.3.8 html5lib-1.1 multitasking-0.0.11 peewee-3.17.0 requests-2.31.0 webencodings-0.5.1 yfinance-0.2.31

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

EXTRACT AND VIEW DATA

In [5]:
import yfinance as yf

start_date = "2017-01-01"
end_date = "2023-06-01"
symbol = "ETH-USD"
df = yf.download(symbol, start=start_date, end=end_date)
df

[*********************100%%**********************]  1 of 1 completed

                   Open         High  ...    Adj Close      Volume
Date                                  ...
2017-11-09   308.644989   329.451996  ...   320.884003   893249984
2017-11-10   320.670990   324.717987  ...   299.252991   885985984
2017-11-11   298.585999   319.453003  ...   314.681000   842300992
2017-11-12   314.690002   319.153015  ...   307.907990  1613479936
2017-11-13   307.024994   328.415009  ...   316.716003  1041889984
...                 ...          ...  ...          ...         ...
2023-05-27  1828.575684  1836.184570  ...  1831.118286  3216737652
2023-05-28  1831.098633  1915.723267  ...  1910.914185  6359610561
2023-05-29  1909.297485  1926.421753  ...  1893.078125  5884674572
2023-05-30  1893.093140  1916.574951  ...  1901.026611  5363439784
2023-05-31  1901.098267  1907.035400  ...  1874.130493  5984512548

[2030 rows x 6 columns]

In [6]:
df.head()

                  Open        High  ...   Adj Close      Volume
Date                                ...
2017-11-09  308.644989  329.451996  ...  320.884003   893249984
2017-11-10  320.670990  324.717987  ...  299.252991   885985984
2017-11-11  298.585999  319.453003  ...  314.681000   842300992
2017-11-12  314.690002  319.153015  ...  307.907990  1613479936
2017-11-13  307.024994  328.415009  ...  316.716003  1041889984

[5 rows x 6 columns]

In [7]:
df.tail(
    
)

                   Open         High  ...    Adj Close      Volume
Date                                  ...
2023-05-27  1828.575684  1836.184570  ...  1831.118286  3216737652
2023-05-28  1831.098633  1915.723267  ...  1910.914185  6359610561
2023-05-29  1909.297485  1926.421753  ...  1893.078125  5884674572
2023-05-30  1893.093140  1916.574951  ...  1901.026611  5363439784
2023-05-31  1901.098267  1907.035400  ...  1874.130493  5984512548

[5 rows x 6 columns]

In [8]:
df.describe()

              Open         High  ...    Adj Close        Volume
count  2030.000000  2030.000000  ...  2030.000000  2.030000e+03
mean   1172.209792  1208.337261  ...  1172.762798  1.254646e+10
std    1154.506297  1189.059211  ...  1154.006117  1.048236e+10
min      84.279694    85.342743  ...    84.308296  6.217330e+08
25%     220.055286   226.203495  ...   220.008633  4.842797e+09
50%     620.317993   646.773285  ...   624.135345  9.956447e+09
75%    1806.723480  1839.738556  ...  1807.757782  1.749749e+10
max    4810.071289  4891.704590  ...  4812.087402  8.448291e+10

[8 rows x 6 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2030 entries, 2017-11-09 to 2023-05-31
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       2030 non-null   float64
 1   High       2030 non-null   float64
 2   Low        2030 non-null   float64
 3   Close      2030 non-null   float64
 4   Adj Close  2030 non-null   float64
 5   Volume     2030 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 111.0 KB

Working With Returns